### ISSUE TITLE
License of sample skin

### ISSUE THREAD

**Issue by Fironet** [deathcrafter/PluginHotInput#2]
Thanks for the plugin, seems to be very little discussed despite its benefits so didn't become aware of it until recently.

Was just wondering if you'd consider relicensing the sample `.rmskin` code (particularly for the Lua demo) in a more permissive open source license, such as CC BY-NC, rather than (or as a separate version to) the current CC BY-NC-SA. That is, keeping the attribution and non-commercial aspects but not the ShareAlike aspect.

As unlike other Creative Common licenses the SA requirement from what I have read means any code base that is combined with such SA code/derivative modifications has to become itself entirely licensed as SA, while I'd prefer to keep a more permissive open source license when distributing my code as a whole.

**Comment by deathcrafter** [comment]
I don't care about the license of anything I make public. You can do what you like with it and distribute it as you please. I just added the license from gh templates in haste.

**Comment by Fironet** [comment]
> I don't care about the license of anything I make public. You can do what you like with it and distribute it as you please. I just added the license from gh templates in haste.

Ah, okay. I suppose it wouldn't matter if it was even a standard MIT open source license in that case.

Just to have some linkable relicensed version would it be too much to ask if you minded reposting as a comment here this zip I made with the adjusted license line?

[MultilineInput.zip](https://github.com/user-attachments/files/17364136/MultilineInput.zip)

**Comment by deathcrafter** [comment]
Please open a pull request with the proposed changes instead of providing a zip.

**Comment by Fironet** [comment]
Just for clarity, the sample skin per se isn't included in the current repo, only in the Releases section as a `.rmskin` attachment.

I asked around about whether a separate repo branch with a different license file would be suitable but was told it leads to ambiguity and it was suggested it should be defined per file in such a case.

So I could PR a separate branch with both the INI and Lua files with individual license lines, if you like.

---

Otherwise in the zip was just the INI and Lua files with the license metadata line in the INI changed.

> Since the plugin itself is GPL licensed and from what I understand distributing GPL code/dependencies with GPL-compatible code (like MIT or CC) causes the package to then become GPL-licensed as a whole, so I removed the DLL from that attached zip.

**Comment by Fironet** [comment]
So I created a new orphan* [branch](https://github.com/Fironet/PluginHotInput/tree/example-skin) in my fork but there doesn't appear to be a way on my end to create a PR on Github with a new branch, only if the same named branch also exists upstream.

\* Created via: `git switch --orphan "example-skin"` to begin without shared files or commit history from the master branch

**Comment by deathcrafter** [comment]
Hi, Fironet. It's a plugin for Rainmeter which is also GPL licensed, so it wouldn't make any sense to license a plugin otherwise.

About the sample skin, it's just there to show how to do stuff with this plugin and install the plugin and not for editing and sharing. The skin has a number of issues like unicode characters not being recognised and stuff.

So I would suggest creating a different repo if you want to create a skin with the plugin. You can then license it as CC, as it is with other skins.

**Comment by Fironet** [comment]
Yeah it wasn't the plugin I was interested in relicensing just the example skin which was attached in the Release tab, since the CC ShareAlike license specifically is copyleft (unlike other CC licenses) and means any say Lua code I make separately for a skin, under say MIT license, gets overridden by ShareAlike when integrated as an adaptation (so anyone wanting to use other bits of my code for their purposes, even non-Rainmeter, would be forced to license as ShareAlike, too, to my understanding).

> _About the sample skin, it's just there to show how to do stuff with this plugin and install the plugin and not for editing and sharing_

I actually discovered the plugin as the popular Droptop Four suite utilizes a direct modification of the Lua example. They then licensed all their source code as CC BY-NC-SA.

But anyway, if there's not enough interest I'll just close the issue. Thanks again for the plugin.

> Side note: final packaged `rmskin` skins that include the DLL plugin would possibly always get overridden by the copyleft GPL license since the plugin itself is GPL, but not for the source code of a skin per se (unless it mixed in code from a copyleft license like GPL, or CC SA like the example skin).
